create table post (id integer not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id integer, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id integer not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id integer not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id integer, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id integer not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id integer, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id integer not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
create table post (id bigint not null auto_increment, content TEXT, creation_date datetime not null, last_update_date datetime not null, topic_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table roles (id integer not null auto_increment, name varchar(20), primary key (id)) engine=InnoDB;
create table sections (id bigint not null auto_increment, description varchar(150), name varchar(50), primary key (id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, closed bit, content TEXT, creation_date datetime not null, last_update_date datetime, title varchar(50), views integer, section_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user_roles (user_id bigint not null, role_id integer not null, primary key (user_id, role_id)) engine=InnoDB;
create table users (id bigint not null auto_increment, email varchar(50), password varchar(120), username varchar(20), primary key (id)) engine=InnoDB;
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table post add constraint FKg8ln3nj8tjclai0nuvpw5s5uw foreign key (topic_id) references topic (id);
alter table post add constraint FK7ky67sgi7k0ayf22652f7763r foreign key (user_id) references users (id);
alter table topic add constraint FK79tub9p67dbbdjsxmeig82eva foreign key (section_id) references sections (id);
alter table topic add constraint FK3qd4k7we4cdll00i6x84afhi8 foreign key (user_id) references users (id);
alter table user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles (id);
alter table user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users (id);
